# Generated by Django 4.2.5 on 2024-01-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
